### PR TITLE
fix: prevent login TextFields from scaling with text

### PR DESCRIPTION
**Pull request by N7-X**
Login TextFields scaled with the content, if the typed text was longer than the default width. 
This ends up looking odd if a password (for example) is very long, so only one TextField is filling the width of the screen. 

Added a maximum size to the textFields, closely matched to the default, and checked for adverse effects.

### CODE REVIEW

**Comment by diegoberaldin** [comment]
I understood the issue (my bad!) however it's better not to block the dimensions of the text field to a fixed size.

It's better to put a horizontal padding to their container and let them expand up to the maximum width, safe for the padding. Since I can not put suggestions in the review, because those lines are not impacted by your changes, I am closing this one and reopen another one for you.

**Comment by N7-X** [comment]
Oh, I should have realized that!  Thanks for keeping me honest :slightly_smiling_face:

**Comment by diegoberaldin** [comment]
Sorry, I really hate closing other people's contributions (even in my non-OSS dev life) but this time it was really easier done than explained.

**Comment by N7-X** [comment]
It's all good - I fully understand and support it :+1: 

I just shook my head at myself for not realizing that, as I've been testing things just like that in little Compose tests on the side. 
Probably just means my mind is about done for the day.

**Pull request closed without merging**
