### PR TITLE
enhancement: post opening and initial load

### PR DESCRIPTION
**Pull request by diegoberaldin**
There was still a flicker when opening a post (which occasionally the refresh indicator appearing) because of two reasons:

- a search field value changed event was triggered, causing an additional refresh
- if there were no comments, `canFetchMore` was equally `true` so immediately after `loading` became `false`, the "fake item" used for pagination triggered in any case a new remote fetch. 

This PR fixes these issues by:
- dropping the first search event (applied to all screens with the similar construct)
- ensuring `canFetchMore` is `false` if there are no items to fetch and this is known beforehand (specific for post detail screen).

### CODE REVIEW

**Comment by diegoberaldin** [comment]
This partially reverts #1078 but I've verified that the final desired behaviour is preserved.

**Comment by N7-X** [comment]
All looks good to me too!  Glad you found a better way to fix it - it actually seems more responsive to me now.

**Comment by diegoberaldin** [comment]
I didn't want to touch the "Explore" section, I was trying to improve the post detail actually... but since the logic was similar I aligned everything. Thank you indeed for the double check and have a nice weekend!

**Comment by N7-X** [comment]
Makes perfect sense to me!  I appreciate it, and hope you have a nice weekend as well! 

PS:  If you're concerned about improving any changes I've made, please don't worry about it.  I'm happy to learn and explore, and it's really quite difficult to hurt my feelings by accident. 
I'm just happy to help out to the best of my abilities, and hopefully those abilities keep improving :slightly_smiling_face:

**Comment by diegoberaldin** [comment]
Ok, same applies for me: change whatever you want, software can always be improved.

**Pull request merged**
