### PR TITLE
fix: share image as file

### PR DESCRIPTION
**Pull request by N7-X**
This PR addresses #1000 where sharing an image as a file in the release builds would not work. 
This was difficult to track down, but I finally figured out that that when `ShareImageBottomSheet` was closed and cleared from memory, it was also interrupting the execution of `ZoomableImageViewModel.shareFile()`. 
This was likely not happening under the debug builds, as those items are held in memory.

The `NotificationCenterEvent`s were moved into `ZoomableImageScreen` and triggered by events from `ShareImageBottomSheet`.
Additionally, I tried removing the delay in `ZoomableImageViewModel.shareFile()` and placing the entire image download into the `Dispatchers.IO` thread, with the UI work executing on a call to the `Dispatchers.Main` thread. 
I'm not 100% sure this was done correctly, but I _think_ everything else is solid.

### CODE REVIEW

**Comment by diegoberaldin** [comment]
Kudos for finding the cause of the bug... but I think that solving this another issue was introduced.

Did you try, e.g., one of the following:
- putting the app in background, opening another app, then going back to Raccoon it when you have the `ShareImageBottomSheet` opened?
- locking the screen and unlocking it when you have `ShareImageBottomSheet` opened?

There is an issue with **state restoration** in the Voyager library which should make it crash under those circumstances because blocks are not supported as properties of `Screen` implementations (and `onShareSelection` is declared as a constructor property).

Yes, a library which imposes such a limitation is very difficult to use, but on Compose Multiplatform the choice one year ago was very limited.

**Comment by diegoberaldin** [comment]
Btw, on the other hand, it was correct to remove that delay (which was a clumsy hack to solve the issue) and moving IO operations to `Dispatchers.IO`.

**Comment by N7-X** [comment]
I can confirm that this PR will cause a crash when putting it in the background.  Locking the screen seems to be okay (API 29 / Emulated) but that absolutely needs to be addressed. 

Thank you!  That's some incredibly helpful information that would have probably frustrated and confused users if you had not caught it. 

The positive side of that hack is that it really helped with the discovery of the issue, as it timed out after the `ShareImageBottomSheet` closed, making the behavior very repeatable. 
This would have been much harder to find if it was also inconsistent, so ultimately I think it was a good thing :+1:

**Comment by diegoberaldin** [comment]
Another thought: the coroutine scope where `shareFile` is called in `ZoomableImageViewModel` is getting canceled when the bottom sheet visibility changes. That coroutine scope is the `screenModelScope` associated to the view model (see the `subscribe... launchIn(this)` part), so if `onDispose` gets called on the view model then the scope is canceled and no new jobs can be launched. That must be the reason.

**Comment by diegoberaldin** [comment]
A possible solution (but here is midnight so I may be totally on the wrong path) would be to externalize the "download / save to gallery / share" sequence of operations to a different component which is not tied in any way to the scope of the view model.

This can be a singleton **use case** (because it combines various calls to helpers/repositories) and the failure could be handled via a notification (`NotificationCenterEvent`) to just display an error message, like it does now after all.

**Comment by N7-X** [comment]
> Another thought: the coroutine scope where `shareFile` is called in `ZoomableImageViewModel` is getting canceled when the bottom sheet visibility changes. That coroutine scope is the `screenModelScope` associated to the view model (see the `subscribe... launchIn(this)` part), so if `onDispose` gets called on the view model then the scope is canceled and no new jobs can be launched. That must be the reason.

This worked beautifully! 
I'm still glad I went through all that trouble with the original solution, because now I understand so much more about the state -> event loop in Compose. 
**Thank you** for your advice and recommendations!!

**Comment by N7-X** [comment]
Alright, I'm pretty sure this reverts all the breaking changes and implements the correct root cause fix. 
Huge thanks for pointing that out!!  To my eyes, I think this is finally good to go. 

Filing these experiences in the back of my head for the future.  Each time we go through something like this, it makes me a better KMP programmer.

**Comment by N7-X** [comment]
> A possible solution (but here it is midnight so I may be totally on the wrong path) would be to externalize the "download / save to gallery / share" sequence of operations to a different component which is not tied in any way to the scope of the view model.
> 
> This can be a singleton **use case** (because it combines various calls to helpers/repositories) and the failure could be handled via a notification (`NotificationCenterEvent`) to just display an error message, like it does now after all. I would put this response to `NotificationCenterEvent` in the `ZoomableImageScreen`, in a scope obtained as `rememberCoroutineScope()` so tied to the lifecycle of the UI itself).

I missed this. 
Hmm...  I think this is a better long term solution. 
One thing that crossed my mind earlier is that this downloads the image each time and saves a new copy to the local drive. 
Ideally, it could pull the already cached image (can it, or is that a coil issue?) and share that version to cut down on network and storage IO. 

So theoretically, we could combine all of these changes into one overhaul of this section. 
It might be worth creating an issue for the roadmap.  Especially if we need to depend on the coil update for this.

**Review by diegoberaldin — APPROVED** [review]

**Comment by diegoberaldin** [comment]
Yes, better create an issue so that we remember doing so. Coil (even Coil2) can definitely be used to just download the image (or retrieve it from cache) instead of downloading and renderingn afterwards.

BTW I'm accepting this because it solves the issue for now. The  new scope we create gets never canceled but the job always terminates so theoretically there should be no leaks.

**Pull request merged**
